# The endpoint of the Azure AI Foundry project where your Agent will be created. It can be found in the project overview page. 
project_endpoint: 

# The name of model deployment to be used for your Agent.
model_name: 

# The connection name of the above resource when added in the Azure AI Foundry portal to your project
translator_resource_connection_name: 

# the region when the translator resource/AI service resource was created. 
translator_resource_region:

# Go to the page of above connection in the Azure AI Foundry portal, then construct the connection ID by append "/connections/<language_resource_connection_name>" to the wsid parameter value in the page URL.
# For example, if the connection page URL contains "wsid=/subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.CognitiveServices/accounts/<account_name>/projects/<project_name>", 
# Then the connection ID is /subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.CognitiveServices/accounts/<account_name>/projects/<project_name>/connections/<language_resource_connection_name>
connection_id: